M7R0
I%Kemiy6(%%loadG%"MG%'afstemG%(tabularG%"mG%"nG6)%(libLoadG%*classPathG%-elemen
tsPathG%%libMG%*libAfstemG%+ModuleLoadG%-ModuleUnloadG(w,6"6$%.mapleBasePathG%(
libPathG6"F4C*>8$-%+kerneloptsG6#%)mapledirG>8%-%$catG6$F;Q4/data/kemi/kemi.jar
F4>T%-%0define_externalG6(.T'/%&CLASSGQ9com.oscarspalk.kemi.KemiF4/%*CLASSPATHG
FA%%JAVAG'.%)moleculeG%'stringG'.%'RETURNG%'doubleG>T)-FI6(.T+FMFPFR'.%%pathGFV
'FXFV>T--FI6*.T/FMFPFR'.%)leftSideGFV'.%*rightSideGFV'.%&depthG&%(integerG6#""%
F^o>T1-FC6$F;Q9/data/kemi/elements.jsonF4-Ffn6#FcpOF4F4F462%6_thismoduledefinit
ionGF4F/%%libMGF&%"MGF,%(libLoadGF%%%loadGF0%*libAfstemGF'%'afstemGF.%-elements
PathG6#""!6+7'Q@/home/oscar/maple_kemi/kemi.mplF4"#H"$D'"%58"#O7'Fgq"#I"$U'"$y'
"#J7'FgqF`r"$"p"$T(F`r7'Fgq"#K"$[("$w)"#V7'Fgq"#L"$$))"%85Fhr7'Fgq"#M"%?5"%*>"F
hr7'Fgq"#N"%17"%n7Fhr7'FgqF[r"%r7"%"H""#?7'Fgq"#P"%&H"Fdq"#_%*protectedGw,6#%&i
nputGF46"F4O-FG6#-%'StringG6#9$F4F46&F[qF4F/F\q6#"""6$7'Fgq"#:"$e$"$0%F[r7'Fgq"
#;"$r$"$'RF\tF]tw,6%FgoFjo>F]p"#]6%%&side1G%&side2G%'resultG6"F4C&>F;Fet>FA-Fft
6#9%>8&-FG6%F;FA9&O-%&parseG6#FevF4F46&F[qF4F0F`q6#""$6'7'Fgq"")"$l""$\$F[r7'Fg
q""*"$4#"$L#F`r7'Fgq"#5"$V#"$o#F`r7'Fgq"#6"$y#"$<$F`r7'Fgq"#7"$@$"$S$F\tF]tGF]t
w,6$%$molG%,formelEnhedG6#FU6"F4C$>F;-FGFbvO*&FhtF[uF;F[uF4F46&F[qF4F&F]q6#""#6
%7'Fgq"#>"$9%"$2&F[r7'FgqFhs"$Z%"$s%F`r7'Fgq"#@"$z%"$)\F\tF]tw,6$%&gramsGFhxFix
6"F4C$>F;F]yO*&FhtF[uF;!""F4F46&F[qF4F&F]q6#Fby6%7'Fgq"#C"$;&"$8'F[r7'Fgq"#D"$^
&"$w&F`r7'Fgq"#E"$$e"$/'F\tF]t)f*6#'F]o<%FdqFV%'symbolGF46$%.call_externalG-FI6
(F_qFM/FQQI/home/oscar/maple2022/data/kemi/kemi.jarF4FR'F]oFV'FYFVF4-F]\l6("0S1
[En>S""0!)yyGn>S"QG(Ljava/lang/String;)Ljava/lang/String;F4Fa\l%&falseG9"F4F4F4
F4GF4QN/home/oscar/maple2022/data/kemi/elements.jsonF4F4f*6#'FUFj[lF46$F]\l-FI6
(F]qFMF`\lFR'FUFV'FYFZF4-F]\l6("0K1[En>S""0syyGn>S"Q6(Ljava/lang/String;)DF4Fa
\lFi\lFj\lF4F4F4F4f*6%'FgoFj[l'FjoFj[l'F]pF^pF46$F]\l-FI6*FaqFMF`\lFR'FgoFV'Fjo
FVF]^lFc\lF4-F]\l6("0[1[En>S""0))yyGn>S"QZ(Ljava/lang/String;Ljava/lang/String;
I)Ljava/lang/String;F4Fa\lFi\lFj\lF4F4F4F4w,F4F46"F4-FGF4F4F46&F[qF4F%F_q6#Fdq6
$7'Fgq"#T"%k8"%(R"F[r7'Fgq"#U"%z8"%%Q"FhsF4w,F4F46"F4F4F4F46$F[qF46#Fdq6#7'Fgq"
#W"%?9"%Q9F[rF4b6#%+thismoduleGF+6#%(packageGF$F46#Q*For~kemi.F4F4F4F4F4
